- block:
  - name: Download Elasticsearch
    get_url:
      url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.2.tar.gz
      dest: /tmp/

  - name: Extract Elasticserach
    unarchive:
      src: /tmp/elasticsearch-6.8.2.tar.gz
      dest: /mnt/
      remote_src: yes

  - name: Change ownership of elasticsearch folder
    file:
      path: "{{ elastic_home }}"
      state: directory
      recurse: yes
      owner: "{{ elastic_user }}"
      group: "{{ elastic_user }}"

  
  - name: Add Elasticsearch service file
    template:
      src: elasticsearch.service.j2
      dest: /etc/systemd/system/elasticsearch.service

  - name: Start Elasticserach
    systemd:
        name: elasticsearch
        state: started
        daemon_reload: yes
        
  
  
  become: true
  become_method: sudo
  become_user: root