- block:
  - name: Download Elasticsearch
    get_url:
      url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.8.2.tar.gz
      dest: /home/ubuntu/

  - name: Extract Elasticserach
    unarchive:
      src: /home/ubuntu/elasticsearch-6.8.2.tar.gz
      dest: /mnt/
      remote_src: yes
      owner: ubuntu
      group: ubuntu
  
  - name: Add Elasticsearch service file
    template:
      src: elasticsearch.service.j2
      dest: /etc/systemd/system/elasticsearch.service

  - name: Start Elasticserach
    systemd:
        name: elasticsearch
        state: started
        daemon_reload: yes
        
  
  
  become: true
  become_method: sudo
  become_user: root